### ISSUE TITLE
signing-key.jks: No such file or directory

### ISSUE THREAD

**Issue by JensRoggeband** [victorbnl/build-signed-apk#4]
Hey Victor B!
I'm using your action, but since your last commits on `main`, it seems to be broken for me.

Without changing anything from version 94e3f1999eeed647aea6aa65cafef5d490c3bcb8
I now get `-Pandroid.injected.signing.store.file=/home/runner/work/<my-project-name>/<my-project-name>/signing-key.jks: No such file or directory` on every build at step:

```
- shell: bash
      working-directory: ${{ inputs.gradlew_dir }}
      run: |
        ./gradlew build
        ./gradlew assembleRelease
       ....
```

**Comment by marie-bnl** [comment]
Can you send your step definition?

**Comment by JensRoggeband** [comment]
Sure

```yml
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build debug signed APK
      uses: victorbnl/build-signed-apk@main
      with:
        keystore_b64: ${{ secrets.DEBUG_KEYSTORE_BASE64 }}
        keystore_password: ${{ secrets.DEBUG_KEYSTORE_PASSWORD }}
        key_alias: ${{ secrets.DEBUG_ALIAS }}
        key_password: ${{ secrets.DEBUG_KEY_PASSWORD }}
```
